class_specific_rules:
  grade_1_to_5:
    belt_required: false
    shoe_type: velcro_shoes_allowed
    tie_required: false
  grade_6_to_8:
    belt_required: true
    shoe_type: formal_shoes
    tie_required: true
  grade_9_to_12:
    belt_required: true
    blazer_required: true
    shoe_type: formal_shoes
    tie_required: true
color_rules:
  belt:
    allowed_colors:
    - black
    - dark_brown
    buckle_color:
    - silver
    - gold
    - black
    material:
    - leather
    - synthetic
    required: true
  blazer:
    allowed_colors:
    - dark_blue
    - black
    - grey
    buttons:
    - silver
    - gold
    - matching
    pattern:
    - solid
    required: false
  shirt:
    allowed_colors:
    - white
    - light_blue
    - cream
    collar_type:
    - regular
    - mandarin
    pattern:
    - solid
    - thin_stripes
    required: true
    sleeve_type:
    - full_sleeve
    - half_sleeve
  shoes:
    allowed_colors:
    - black
    - dark_brown
    laces:
    - black
    - brown
    - white
    required: true
    sole_color:
    - black
    - brown
    - white
    type:
    - formal_shoes
    - school_shoes
  socks:
    allowed_colors:
    - white
    - black
    - dark_blue
    length:
    - ankle
    - crew
    - knee_high
    pattern:
    - solid
    required: true
  student_id_card:
    allowed_colors:
    - white
    - light_blue
    - cream
    background_colors:
    - blue
    - white
    - red
    position: visible_on_chest_or_pocket
    required: true
    text_colors:
    - black
    - dark_blue
  tie:
    allowed_colors:
    - red
    - blue
    - green
    - maroon
    pattern:
    - solid
    - stripes
    - school_pattern
    required: false
    width:
    - regular
  trousers:
    allowed_colors:
    - black
    - dark_blue
    - dark_grey
    - khaki
    fit_type:
    - regular
    - straight
    length:
    - full_length
    pattern:
    - solid
    required: true
created_date: '2025-08-27T00:23:59.553158'
detection_parameters:
  color_tolerance: 0.15
  compliance_scores:
    acceptable: 0.6
    excellent: 0.95
    good: 0.8
    poor: 0.4
    unacceptable: 0.2
  confidence_threshold: 0.5
  minimum_size:
    face: 100
    shirt: 100
    shoes: 80
    student_id_card: 50
    trousers: 100
  nms_threshold: 0.4
optional_items:
- tie
- blazer
- sweater
- cap
- badge
required_items:
- student_id_card
- shirt
- trousers
- shoes
- belt
- socks
rule_name: Standard School Uniform Rules
seasonal_rules:
  summer:
    blazer_required: false
    months:
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    shirt_sleeve: half_sleeve
    tie_required: false
  winter:
    blazer_required: true
    months:
    - 10
    - 11
    - 12
    - 1
    - 2
    - 3
    shirt_sleeve: full_sleeve
    sweater_allowed: true
    tie_required: true
special_day_rules:
  assembly_day:
    blazer_required: true
    days:
    - monday
    shoes_polish: high
    tie_required: true
  sports_day:
    shirt: sports_shirt
    shoes: sports_shoes
    trousers: sports_shorts
version: '1.0'
violation_penalties:
  missing_belt:
    action: warning
    message: Belt नहीं पहनी है
    penalty: low
  missing_shoes:
    action: deny_entry
    message: Proper shoes नहीं पहने हैं
    penalty: high
  missing_student_id:
    action: deny_entry
    message: Student ID card नहीं दिख रहा है
    penalty: high
  wrong_shirt_color:
    action: warning
    message: Shirt का color correct नहीं है
    penalty: medium
  wrong_trouser_color:
    action: warning
    message: Trouser का color correct नहीं है
    penalty: medium
